### ISSUE TITLE
sdk证书路径修改到resources目录下，如何获取文件？

### ISSUE THREAD

**Issue by YClimb** [YClimb/wxpay-sdk#2]
![11111](https://user-images.githubusercontent.com/12524999/56572887-84710080-65f2-11e9-8487-c10f451eb313.png)

**Comment by YClimb** [comment]
在微信支付 sdk 中修改获取证书文件方法即可

**Comment by jy05568536** [comment]
> 在微信支付 sdk 中修改获取证书文件方法即可

具体怎么操作过？遇到同样的问题，打成jar包后获取不到证书

**Comment by duxingyao** [comment]
springboot打成jar后获取classpath下文件失败

使用如下代码：

ClassPathResource resource = new ClassPathResource("application.yml");
File file = resource.getFile();

未打包时可以获取到文件，打包后报错

Caused by: java.io.FileNotFoundException: class path resource [application.yml] cannot be resolved to absolute file path because it does not reside in the file system: jar:file:/D:/sunmnet/JetBrains/workspace/bigdata-parse-table/target/bigdata-parse-table-1.0-SNAPSHOT.jar!/BOOT-INF/classes!/application.yml
        at org.springframework.util.ResourceUtils.getFile(ResourceUtils.java:215) ~[spring-core-4.3.12.RELEASE.jar!/:4.3.12.RELEASE]
        at org.springframework.core.io.AbstractFileResolvingResource.getFile(AbstractFileResolvingResource.java:53) ~[spring-core-4.3.12.RELEASE.jar!/:4.3.12.RELEASE]
        at hello.whz.Application.lambda$lookup$0(Application.java:30) [classes!/:1.0-SNAPSHOT]
        at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:732) [spring-boot-1.5.8.RELEASE.jar!/:1.5.8.RELEASE]
        ... 14 common frames omitted

这是因为打包后Spring试图访问文件系统路径，但无法访问JAR中的路径。
因此必须使用resource.getInputStream()

ClassPathResource resource = new ClassPathResource("application.yml");
InputStream inputStream = resource.getInputStream();
